# Generated by Django 5.0.6 on 2025-01-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0005_category_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='product2',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='product2',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='product2',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
