# Generated by Django 5.0.6 on 2025-01-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_product2_img2_product2_img3_product2_img4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
